config/routes.rb
Rails.application.routes.draw do
  root "users#index"
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :posts, except: [:index], shallow: true do
    resources :comments, only: [:update, :create, :destroy]
  end
  resources :relationships, only: [:create, :destroy]
  resources :sessions, only: [:index, :new, :create, :destroy]
  get '/login', to: 'users#index'
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :comments, dependent: :destroy
  default_scope -> { order('created_at DESC') }
  validates :user_id, presence: true
  has_attached_file :image, styles: { medium: "500x500>", thumb: "250x250>" }, presence: true
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

  # Returns posts from the users being followed by the given user.
  def self.from_users_followed_by(user)
    followed_user_ids = "SELECT followed_id FROM relationships
                         WHERE follower_id = :user_id"
    where("user_id IN (#{followed_user_ids}) OR user_id = :user_id",
          user_id: user.id)
  end
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
  validates :follower_id, presence: true
  validates :followed_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates :email, presence: true, uniqueness: true
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy

  has_many :relationships, foreign_key: "follower_id", dependent: :destroy
  has_many :followed_users, through: :relationships, source: :followed

  has_many :reverse_relationships, foreign_key: "followed_id", class_name: "Relationship", dependent: :destroy
  has_many :followers, through: :reverse_relationships, source: :follower

  has_attached_file :image, styles: { medium: "500x500>", thumb: "250x250>" }, presence: true
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
  has_attached_file :bannerimg, styles: { medium: "500x500>", thumb: "250x250>" }, presence: true
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

   def following?(other_user)
     relationships.find_by(followed_id: other_user.id)
   end

   def follow!(other_user)
     relationships.create!(followed_id: other_user.id)
   end

   def unfollow!(other_user)
     relationships.find_by(followed_id: other_user.id).destroy
   end

   def feed
    Post.where("user_id = ?", id)
    Post.from_users_followed_by(self)
   end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

  helper_method :current_user

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def authorize
    redirect_to root_path, alert: 'Not authorized - must be logged in!' if current_user.nil?
  end

  def signup
    redirect_to root_path, alert: 'Sign up to leave a comment!' if current_user.nil?
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:edit, :update, :destroy]
  before_action :signup, only: [:show]

  def show
  end

  def new
    @comment = Comment.new
  end

  def create
    @comment = Comment.new(comment_params)
    @comment.user = current_user
    @comment.post_id = params[:post_id]
    if @comment.save
      redirect_to :back, notice: "Your comment was published!"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @comment.update_attributes(comment_params)
      redirect_to post_path(@comment.post), notice: "Your comment was saved!"
    else
      render :edit
    end
  end

  def destroy
    post = @comment.post
    @comment.destroy
    redirect_to post
  end

  private

  def set_comment
    @comment = Comment.find(params[:id])
  end

  def comment_params
    params.require(:comment).permit(:body, :user_id, :post_id, :user_name)
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authorize, except: [:index, :show]

  def index
    @posts = Post.all
  end

  def show
    @comment = Comment.new
  end

 def new
    @post = Post.new
  end

  def create
    @createpost = User.find(session[:user_id])
    @createpost.posts.create(post_params)
    if @createpost.save
      redirect_to root_path, notice: "Your post has been saved."
    else
      @feed_items = []
      render :new
    end
  end

  def edit
    unless current_user == @post.user
      flash[:notice] = "Sorry, can't let you do that."
      redirect_to users_path
      return
    end
  end

  def update
    if @post.update_attributes(post_params)
      redirect_to user_path(current_user.id), notice: "Your post has been saved."
    else
      render :edit
    end
  end

  def destroy
    unless current_user == @post.user
      flash[:notice] = "Sorry, can't let you do that."
      redirect_to users_path
      return
    end
    @post.destroy if @post.user == current_user
    redirect_to root_path
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :description, :keyword, :image)
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_action :current_user

  def create
    @user = User.find(params[:relationship][:followed_id])
    current_user.follow!(@user)
    respond_to do |format|
      format.html { redirect_to @user }
      format.js
    end
  end

  def destroy
    @user = Relationship.find(params[:id]).followed
    current_user.unfollow!(@user)
    respond_to do |format|
      format.html { redirect_to @user }
      format.js
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to users_path
    else
      flash.now.alert = 'Invalid login - try again!'
      render :index
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :authorize, except: [:index, :show, :new, :create, :following, :followers]

  def index
    @users = User.all

    if params[:random]
      n = @users.length
      rnd_idx = rand(0...n)
      user = @users[rnd_idx]
      redirect_to "/users/#{user.id}?random=true"
    end

    if current_user
      @post = current_user.posts.build
      @feed_items = current_user.feed.paginate(page: params[:page])
    end
  end

  def show
    @posts = @user.posts
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "You have signed up!"
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
    unless session[:user_id] == @user.id
      flash[:notice] = "You don't have access to that account!"
      redirect_to users_path
      return
    end
  end

  def update
    if @user.update_attributes(user_params)
      redirect_to user_path(current_user.id)
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to root_path
  end

  def following
    @title = "Following"
    @user = User.find(params[:id])
    @users = @user.followed_users.paginate(page: params[:page])
    render 'show_follow'
  end

  def followers
    @title = "Followers"
    @user = User.find(params[:id])
    @users = @user.followers.paginate(page: params[:page])
    render 'show_follow'
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :age, :bio, :email, :location, :image, :bannerimg, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def gravatar_for(user)
    gravatar_url = user.image
    if user.image?
      image_tag(gravatar_url, alt: user.name, class: "gravatar")
    else
      image_tag "noprofile.png", class: "gravatar"
    end
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ClimbOn Adventure Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href="https://fonts.googleapis.com/css?family=Vollkorn" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Droid+Sans" rel="stylesheet">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</head>
<body>
  <nav class="navbar navbar-default navbar-fixed-top">
    <div class="navbar-header">
      <a class="navbar-brand" href="/">
        <%= image_tag("climb-on-logo.png", height: "30px", class: "desaturate below-break", alt: "Climbon") %>
      </a>
      <button type="button" id="dropdown-button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div class="collapse navbar-collapse">
      <div class="container">
        <ul class="nav navbar-nav navbar-right">
          <% if current_user %>
            <li id="navlink">
              <a href="/">Home</a>
            </li>
            <li id="navlink">
              <%= link_to 'Profile', user_path(current_user.id)%>
            </li>
            <li id="navlink">
              <%= link_to "Explore", '/users?random=true' %>
            </li>
            <li id="navlink">
              <%= link_to 'Sign Out', session_path('dummy'), method: :delete %>
            </li>
          <% else %>
            <li id="navlink">
              <%= link_to "Explore", '/users?random=true' %>
            </li>
            <li id="navlink">
              <a href="/">Log in</a>
            </li>
            <li id="navlink">
              <%= link_to 'Sign up', new_user_path %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>

<%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<div class="container">
  <%= form_for @post do |f| %>
  <div>
    <%= f.text_field :title, :required => true, placeholder: "Title", :maxlength => 90, :class =>"form-control" %>
  </div>
  <br>
  <div>
    <%= f.text_area :description, :required => true, size:"5x10", placeholder: "Write something...", :class =>"form-control text-area" %>
  </div>
  <br>
  <div class="form">
    <%= f.label :image, :class => "title" %>
    <%= f.file_field :image, :class => "title" %>
  </div>
  <br>
  <%= f.submit "Post", :class => "btn btn-primary" %>
  <% end %>
</div>

app/views/posts/edit.html.erb
<div class="container">
  <%= link_to 'Back', user_path(@post.user), :class => "btn btn-danger btn-xs" %>
  <h1 class="title">Edit Post</h1>

  <%= render 'form' %>

</div>

app/views/posts/new.html.erb
<div class="container">
  <%= link_to 'Back', user_path(current_user), :class => "btn btn-danger btn-xs" %>
  <h1 class="title">New Post</h1>

  <%= render 'form' %>

</div>

app/views/posts/show.html.erb
<div class="container">
  <p id="notice" class="title"><%= notice %></p>
  <div class="panel post panel-default">
    <div class="comment-title">
      <div class="panel-title pull-left">
        <%= @post.title %>
      </div>
      <div class="panel-title pull-right">
        Posted <%= time_ago_in_words(@post.created_at) %> ago
      </div>
      <div class="clearfix"></div>
      </div>
    <div class="panel-body">
    <% if @post.image? %>
        <div class="col-md-6"><%= image_tag @post.image, class: "post-img img-responsive" if @post.image? %></div>
      <div class="postcontent col-md-6"><%= simple_format(@post.description)%></div>
    <% else %>
      <div class="postcontent col-md-11"><%= simple_format(@post.description)%></div>
    <% end %>
    </div>
  <%= link_to "Go Back", user_path(@post.user) %>
  <% if current_user %>
    <%= link_to "/ Edit post /", post_path + '/edit' if current_user == @post.user %>
    <%= link_to "Delete post", post_path, method: :delete, data: { confirm: "Are you sure you want to delete?" } if current_user == @post.user %>
  <% else %>
  <% end %>
  </div>
</div>

<div class="container">
  <% @post.comments.each do |comment| %>
    <div class="panel post panel-default">
        <div class="comment-title"><%= link_to gravatar_for(comment.user), comment.user %>
      <% if current_user %>
        <span class= "pull-right"><%= link_to "Delete", comment_path(comment), method: :delete, data: { confirm: "Are you sure you want to delete?" }, :class => "btn btn-danger btn-xs" if current_user.id == comment.user_id %></span>
      <% else %>
      <% end %>
        <span class="fixname postname"><%= link_to comment.user.name, comment.user %></span>
        </div>
        <p id="fixmargin">Posted <%= time_ago_in_words(comment.created_at) %> ago</p>
        <p class="fixcomment container"><%= comment.body %></p>
    </div>
  <% end %>
  <div><%= link_to "Log in to say something!", root_path, :class => "btn btn-primary", :id => "fixmargin" if !current_user %></div>
  <% if current_user %>
      <%= form_for [@post, @comment] do |f| %>
        <div class="panel panel-info">
          <%= f.text_area :body, size:"3x3", :class => "form-control text-area", :required => true, placeholder: "Say something..." %>
        </div>
          <%= f.submit "Submit", :class => "btn btn-primary", :id => "fixmargin" %>
      <% end %>
  <% else %>
  <% end %>
</div>

app/views/relationships/create.js.erb
$("#follow_form").html("<%= escape_javascript(render('users/unfollow')) %>")
$("#followers").html('<%= @user.followers.count %>')

app/views/relationships/destroy.js.erb
$("#follow_form").html("<%= escape_javascript(render('users/follow')) %>")
$("#followers").html('<%= @user.followers.count %>')

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <div class="container col-xs-12">
    <ul class="feedposts">
      <%= render partial: 'shared/feed_item', collection: @feed_items %>
    </ul>
  </div>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_feed_item.html.erb
<li id="<%= feed_item.id %>">
  <div class="container col-xs-12">
    <div class="panel post panel-default col-xs-12">
      <div class="user-show-title"><%= link_to gravatar_for(feed_item.user), feed_item.user %>
        <% if current_user %>
          <span class= "pull-right"><%= link_to "Delete", feed_item, method: :delete, data: { confirm: "Are you sure you want to delete?" }, :class => "btn btn-danger btn-xs" if current_user == feed_item.user %></span>
        <% else %>
        <% end %>
        <span class="fixname postname"><%= link_to feed_item.user.name, feed_item.user %></span>
      </div>
      <p id="fixmargin">Posted <%= time_ago_in_words(feed_item.created_at) %> ago</p>
      <p class="fixcomment container col-xs-12"><%= feed_item.description %></p>
      <%= link_to 'Show more', post_path(feed_item.id) %>
      <%= link_to '/ Edit post', post_path(feed_item.id) + '/edit' if current_user == feed_item.user %>
    </div>
  </div>
</li>

app/views/shared/_post_form.html.erb
<div>
  <%= form_for(@post) do |f| %>
    <%= f.text_field :title, :required => true, :maxlength => 90, :class => "form-control", placeholder: "Title" %>
    <br>
    <%= f.text_area :description, :required => true, size: "5x5", :class => "text-area form-control", placeholder: "Compose new post..." %>
    <%= f.file_field :image %>
  <%= f.submit "Post", class: "btn btn-large btn-primary" %>
</div>
<% end %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.followed_users.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div>

app/views/shared/_user_info.html.erb
<% if current_user.image? %>
  <%= image_tag current_user.image, :class => "profile-img img-responsive" %>
<% else %>
  <%= image_tag "noprofile.png", :class => "profile-img img-responsive" %>
<% end %>
<div><h2 class="profilename" id="fixmargin"><%= link_to current_user.name, user_path(current_user.id) %></h2></div>
<h4><%= current_user.bio %></h4>
<label>Age:</label>
<span class="userinfo"><%= current_user.age %></span>
<label>Location:</label>
<span class="userinfo"><%= current_user.location %></span>
<p id="fixmargin"><%= pluralize(current_user.posts.count, "post") %></p>

app/views/users/_follow.html.erb
<%= form_for(current_user.relationships.build(followed_id: @user.id), remote: true) do |f| %>
  <div><%= f.hidden_field :followed_id %></div>
  <%= f.submit "Follow", class: "btn btn-large btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<% if current_user %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>
<% else %>
<% end %>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <div class="form-group row">
    <label class="col-2 col-form-label">Name *</label>
    <div class="col-10">
      <%= f.text_field :name, :required => true, :maxlength => 20, :class =>"form-control form-control-sm"%>
    </div>
  </div>
  <div class="form-group row">
    <label class="col-2 col-form-label">Age</label>
    <div class="col-10">
      <%= f.number_field :age, :max => 100, :min => 1, :class =>"form-control"%>
    </div>
  </div>
  <div class="form-group row">
    <label class="col-2 col-form-label">Description</label>
    <div class="col-10">
      <%= f.text_area :bio, :maxlength => 120, :class =>"form-control text-area"%>
    </div>
  </div>
  <div class="form-group row">
    <label class="col-2 col-form-label">Location</label>
    <div class="col-10">
      <%= f.text_field :location, :maxlength => 10, :class =>"form-control"%>
    </div>
  </div>
  <div class="form-group row">
    <label class="col-2 col-form-label">Email *</label>
    <div class="col-10">
      <%= f.text_field :email, :required => true, :class =>"form-control"%>
    </div>
  </div>
  <% if current_user %>
  <% else %>
  <div class="form-group row">
    <label class="col-2 col-form-label">Password *</label>
    <div class="col-10">
      <%= f.password_field :password, :required => true, :class =>"form-control"%>
    </div>
  </div>
  <div class="form-group row">
    <label class="col-2 col-form-label">Confirm Password *</label>
    <div class="col-10">
      <%= f.password_field :password_confirmation, :required => true, :class =>"form-control"%>
    </div>
  </div>
  <% end %>
  <div class="form-group row">
    <label class="col-2 col-form-label">Profile Picture</label>
    <div class="col-10">
      <%= f.file_field :image, :class => "pull-left" %>
      <span><%= f.submit "Submit", :class => "btn btn-primary pull-right" %></span>
    </div>
  </div>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.relationships.find_by(followed_id: @user.id), html: { method: :delete }, remote: true) do |f| %>
  <%= f.submit "Unfollow", class: "btn btn-large" %>
<% end %>

app/views/users/edit.html.erb
<div class="container">
  <%= link_to 'Back', user_path(@user), :class => "btn btn-danger btn-xs", :id => "fixmargin" %>
  <div class="sign-backdrop">
    <h1 class="title inline">Account Settings </h1>
    <%= link_to "Delete yo'self", user_path, method: :delete, data: { confirm: "Are you sure you want to delete your account?" }, :id => "fixmargin", :class => "btn btn-danger btn-xs pull-right" if current_user.id == @user.id %>
    <hr class="linefix">

    <%= render 'form' %>

  </div>
</div>

app/views/users/index.html.erb
<% if current_user %>
  <p id="notice" class="title text-center"><%= notice %></p>
  <h1 class="text-center title" id="fixmargin">Dashboard</h1>
  <div class="container col-xs-8">
    <%= render 'shared/feed' %>
  </div>
  <div class="profile-info col-xs-3 text-center">
    <section>
      <%= render 'shared/user_info' %>
    </section>
    <section>
      <%= render 'shared/stats' %>
    </section>
    <section>
      <%= render 'shared/post_form' %>
    </section>
  </div>
<% else %>
  <div class="mainpage bg">
    <div class="container text-center">
      <span id="alert"><%= alert %></span>
      <h1 class="maintitle">Climb On</h1>
      <h3 class="phrase-title">Re-live your adventures</h3>
      <div class="login form-group">
        <%= form_tag sessions_path do %>
          <div class="field">
            <%= text_field_tag :email, params[:email], placeholder: "Email" %>
          </div>
          <div class="field">
            <%= password_field_tag :password, "", placeholder: "Password" %>
          </div>
          <span class="actions"><%= submit_tag "", :style => "display: none;" %></span>
        <% end %>
        <footer class="text-center">
          &copy; 2017 <span class="name">ibrianfrancisco</span>
        </footer>
      </div>
    </div>
  </div>
<% end %>

app/views/users/new.html.erb
<div class="bg signpage">
<div class="container">
  <div class="sign-backdrop">
<!--     <h2 class="title">Sign Up</h2>
    <hr class="linefix">
 -->
    <%= render 'form' %>

  </div>
</div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="profile-info col-sm-3">
    <div class="container col-sm-12 text-center">
      <div>
        <% if @user.image? %>
          <%= image_tag @user.image, :class => "profile-img" %>
        <% else %>
          <%= image_tag "noprofile.png", :class => "profile-img" %>
        <% end %>
      </div>
      <h2 class="profilename" id="fixmargin"><%= @user.name %></h2>
      <h4><%= @user.bio %></h4>
      <div>
        <label>Age:</label>
        <span class="userinfo"><%= @user.age %></span>
        <label>Location:</label>
        <span class="userinfo"><%= @user.location %></span>
      </div>
      <section>
        <%= render 'shared/stats' %>
      </section>
      <% if current_user %>
        <div>
          <%= render 'follow_form' if current_user.id != @user.id %>
        </div>
        <%= link_to "Account settings", edit_user_path, :class => "btn btn-primary" if current_user.id == @user.id %>
      <% else %>
      <% end %>
      </div>
    </div>

  <div class="container col-xs-9">
    <p id="notice" class="title text-center"><%= notice %></p>
    <h1 class="text-center title" id="fixmargin">My Posts</h1>
    <% if @posts.any? %>
      <% @posts.each do |post| %>
        <div class="panel post col-xs-12">
          <div class="user-show-title">
            <div class="panel-title pull-left">
              <%= post.title %>
            </div>
            <div class="panel-title pull-right">
              Posted <%= time_ago_in_words(post.created_at) %> ago
            </div>
            <div class="clearfix"></div>
          </div>
        <div class="postcontent" id="fixmargin"><%= simple_format(post.description) %></div>
        <%= link_to 'Show more', post_path(post) %>
        <% if current_user %>
          <%= link_to '/ Edit post /', post_path(post) + '/edit' if current_user.id == @user.id %>
          <%= link_to "Delete post", post_path(post), method: :delete, data: { confirm: "Are you sure you want to delete?" } if current_user.id == @user.id %>
        <% else %>
        <% end %>
        </div>
      <% end %>
    <% else %>
      <p class="title text-center">This person hasn't posted anything yet!</p>
    <% end %>
    <div class="text-center">
      <% if current_user %>
        <%= link_to 'Create post', new_post_path, :class => "btn btn-primary", :id => "fixmargin" if current_user.id == @user.id %>
      <% else %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show_follow.html.erb
<% provide(:title, @title) %>
<div class="container">
  <div class="follow-page post">
  <div class="text-center">
  <div>
    <h1 class="profilename" id="fixmargin"><%= @user.name + "'s " + @title %></h1>
  </div>
  <% if @user.image? %>
    <%= image_tag @user.image, :class => "profile-img" %>
  <% else %>
    <%= image_tag "noprofile.png", :class => "profile-img" %>
  <% end %>
  <%= render 'shared/stats' %>
  <%= link_to "View Profile", user_path(@user) %>
  </div>
  <section>
    <ul class="feedposts">
    <% if @users.any? %>
        <% @users.each do |user| %>
          <li><%= link_to gravatar_for(user), user %>
          <%= user.name %></li>
        <% end %>
    <% end %>
    </ul>
  </section>
</div>
</div>